
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.10.16.3-microsoft-standard-WSL2 - x86_64
...
